# dockerfile pro banco de dados
FROM postgres:latest

#ENV POSTGRES_DB=spotify
#ENV POSTGRES_USER=adm
#ENV POSTGRES_PASSWORD=123

COPY banco/script.sql /docker-entrypoint-initdb.d/
COPY banco/dataset.csv /dados/