version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./banco/Dockerfile
    container_name: container_banco
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: container_spark
    ports:
      - 5000:5000
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
